### ISSUE TITLE
Looks like 100-99.9 is calculated wrong to 0.099999999999994 and not to 0.1

### ISSUE THREAD

**Issue by wh1tew0lf** [dr-montasir/mnjs#1]
I saw at code that for calculations for add or sub you use `Number((r - e).toFixed(15));` or `Number((r + e).toFixed(15));`
But if I try `Number((100 - 99.9).toFixed(15));` I get `0.099999999999994` and not `0.1` as expected, so may be it will be good to review calculations logic.

**Comment by dr-montasir** [comment]
Thank you for your precious Time. You are right https://runkit.com/embed/d6chgih3x2bv
The result gives 0.099999999999994
Will try to correct the error in the next version

**Comment by dr-montasir** [comment]
JavaScript and many programming languages follow the IEEE 754 documentation to implement the binary number in the decimal system. The current issue related to part  after decimal point.

Please check the mantissa and ml10pow2 functions in the code. Now we get 0.1 https://runkit.com/embed/m1wfnfdk9c2f (v4.3.1), However, this is not a complete solution, we still have a problem with large numbers https://runkit.com/embed/21yjavym6tod
